site_name: ExploreASL
repo_url: https://github.com/ExploreASL/Documentation
site_url: https://github.com/ExploreASL/Documentation

nav:
    - Home:                   index.md
    - Tutorials:
        - 'Tutorials (Install)':     Tutorials-Install.md
        - 'Tutorials (Execution)':     Tutorials-Execution.md
        - 'Tutorials (Import)':     Tutorials-Import.md
        - 'Tutorials (Processing)':     Tutorials-Processing.md
        - 'Tutorials (Report)':     Tutorials-Report.md
        - 'Tutorials (QC)':         Tutorials-QC.md
        - 'Tutorials (Developer)':         Tutorials-Developer.md    
    - 'Reference manuals':
        - 'Modules':                Modules.md
        - 'Module Import':          Import_Module.md
        - 'Module Structural':      Structural_Module.md
        - 'Module ASL':             ASL_Module.md
        - 'Module Population':      Population_Module.md
        - 'Functions':              Functions.md
        - 'SPM xASL Functions':     SPMxASL.md
        - 'Processing Parameters (dataPar.json)': ProcessingParameters.md
    - FAQ:                    FAQ.md
    - Requirements:           Requirements.md
    - Change Log:             Changes.md
    - License:                License.md
    - About:                  About.md

plugins:
    - search

theme:
  name: material
  logo: img/favicon/brain_icon_500x500.png
  favicon: img/favicon/favicon-96x96.png
  palette:
    scheme: slate
  features:
    - navigation.expand

markdown_extensions:
    - attr_list

extra:
  version:
    provider: mike
