site_name: ExploreASL
nav:
    - Home:               index.md
    - Modules:            Modules.md
    - Module Import:      Import_Module.md
    - Module Structural:  Structural_Module.md
    - Module ASL:         ASL_Module.md
    - Module Population:  Population_Module.md
    - Functions:          Functions.md
    - SPM xASL Functions: SPMxASL.md
    - Tutorials & FAQ:    Tutorials.md
    - Requirements:       Requirements.md
    - License:            License.md
    - About:              About.md

plugins:
    - search
    - awesome-pages

theme:
  name: material

markdown_extensions:
    - attr_list

extra:
  version:
    provider: mike
