site_name: ExploreASL
nav:
    - Home:               index.md
    - Modules:            Modules.md
    - Module Import:      Import_Module.md
    - Module Structural:  Structural_Module.md
    - Module ASL:         ASL_Module.md
    - Module Population:  Population_Module.md
    - Functions:          Functions.md
    - SPM xASL Functions: SPMxASL.md
    - Tutorials & FAQ:    Tutorials.md
    - Requirements:       Requirements.md
    - License:            License.md
    - About:              About.md

plugins:
    - search

theme:
  name: material

markdown_extensions:
    - attr_list

extra:
  version:
    - mike:
        # these fields are all optional; the defaults are as below...
        version_selector: true   # set to false to leave out the version selector
        css_dir: css             # the directory to put the version selector's CSS
        javascript_dir: js       # the directory to put the version selector's JS
        canonical_version: null  # the version for <link rel="canonical">; `null`
                                 # uses the version specified via `mike deploy`